#!/bin/bash

DATASET="weather"
PRED_LEN=192
MODEL="DLinear"
CHECKPOINT_DIR="./checkpoints/${MODEL}/${DATASET}_${PRED_LEN}/"
BASE_LR=0.001
WEIGHT_DECAY=0.0
GATING_INIT=0.01

python main.py DATA.NAME ${DATASET} DATA.PRED_LEN ${PRED_LEN} MODEL.NAME ${MODEL} MODEL.pred_len ${PRED_LEN} TRAIN.ENABLE False TRAIN.CHECKPOINT_DIR ${CHECKPOINT_DIR} TTA.ENABLE True TTA.SOLVER.BASE_LR ${BASE_LR} TTA.SOLVER.WEIGHT_DECAY ${WEIGHT_DECAY} TTA.TAFAS.GATING_INIT ${GATING_INIT}
            